### PR TITLE
Remove database credentials from code

### PR DESCRIPTION
**Pull request by Ezeji**
The change was made:
- Removed database credentials from code since it's best practice to have secrets or credentials in a secured storage off the code.

### CODE REVIEW

**Comment by nuel-emeka** [comment]
Hi Ezeji! Thanks for making these updates to the codebase. Could you point me to where you stored the database credential since you removed it?

**Comment by Ezeji** [comment]
It's a pleasure Emeka and you guys have a great work here, I must commend. Regarding the database credentials which are the credentials I created while working on the codebase updates, I didn't place them in a key vault like Azure or the likes since there's no dedicated key vault store for the project. I, therefore, took it off while adding placeholders with the intent that whoever clones the repo for use can setup a key vault internally and have the credential values placed there while the keys are mapped on code as specified.

**Comment by nuel-emeka** [comment]
I see, that makes sense. The repo was initially private and at that time, we weren't really concerned about leaving the credentials in the codes but we later made it public and forgot to take it out. Thanks for bringing it to our notice and fixing that.

**Comment by Ezeji** [comment]
No worries, thanks for your review.

**Pull request merged**
